spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car_park?createDatabaseIfNotExist=true
    username: root
    password: root

  #JPA Properties
  mvc:
    view:
      prefix: resources/templates
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: TRUE
        format_sql: TRUE


#      Login Levels
#            logging.level.org: WARN
#            logging.level.blog: WARN


      #Show SQL executed with parameter bindings
      #      logging.level.org.hibernate.SQL: DEBUG
#      logging.level.org.hibernate.type.descriptor: TRACE
